package com.mjzeolla.mindsEye.utils

import com.mjzeolla.mindsEye.R

const val EXTRA_BOARD_SIZE = "EXTRA_BOARD_SIZE"
const val EXTRA_GAME_NAME = "EXTRA_GAME_NAME"
val DEFAULT_ICONS = listOf(
        R.drawable.ic_star_yellow,
        R.drawable.ic_emoji_green,
        R.drawable.ic_face_red,
        R.drawable.ic_flight_dark_blue,
        R.drawable.ic_headset_dark_green,
        R.drawable.ic_hiking_dark_red,
        R.drawable.ic_house_blue,
        R.drawable.ic_sports_esports_gray,
        R.drawable.ic_two_wheeler_light_purple,
        R.drawable.ic_surfing_light_blue,
        R.drawable.ic_sports_volleyball_pink,
        R.drawable.ic_sports_football_orange,
)

val SPORTS_ICONS = listOf(
        R.drawable.arrow,
        R.drawable.backboard,
        R.drawable.ball,
        R.drawable.basketball,
        R.drawable.dartboard,
        R.drawable.flag,
        R.drawable.football,
        R.drawable.football__1_,
        R.drawable.football__2_,
        R.drawable.goal,
        R.drawable.running,
        R.drawable.sock,
)

val VIDEO_GAME_ICONS = listOf(
        R.drawable._01_chest,
        R.drawable._02_money_bag,
        R.drawable._03_coins,
        R.drawable._04_gems,
        R.drawable._05_trophy,
        R.drawable._06_sword,
        R.drawable._07_shield,
        R.drawable._08_arrows,
        R.drawable._09_sceptre,
        R.drawable._14_ring,
        R.drawable._16_magician_hat,
        R.drawable._17_bullseye,
        R.drawable._18_arch,
        R.drawable._20_potion,
        R.drawable._21_elixir,
        R.drawable._22_cooking_pot,
        R.drawable._23_key,
        R.drawable._24_heart,
        R.drawable._25_parchment,
        R.drawable._26_spell_book,
        R.drawable._27_stars,
        R.drawable._28_diamond,
        R.drawable._29_map,
        R.drawable._31_feathers,
        R.drawable._34_wood,
        R.drawable._35_crown,
        R.drawable._36_torch,
        R.drawable._37_flag,
        R.drawable._38_hourglass,
        R.drawable._39_bag,
        R.drawable._41_cup,
        R.drawable._42_fire,
        R.drawable._43_thunder,
        R.drawable._44_water,
        R.drawable._45_ice,
        R.drawable._46_leaf,
        R.drawable._50_viking_ship,
        R.drawable._52_apple,
        R.drawable._53_carrot,
        R.drawable._54_ham,
        R.drawable._56_cherries,
)

val ANIMAL_ICONS = listOf(
        R.drawable._01_elephant,
        R.drawable._02_snake,
        R.drawable._04_turtle,
        R.drawable._05_parrot,
        R.drawable._06_panda,
        R.drawable._07_boar,
        R.drawable._08_giraffe,
        R.drawable._09_squid,
        R.drawable._13_beetle,
        R.drawable._17_hedgehog,
        R.drawable._19_ladybug,
        R.drawable._20_dog,
        R.drawable._21_sloth,
        R.drawable._22_rabbit,
        R.drawable._23_crab,
        R.drawable._25_zebra,
        R.drawable._27_horse,
        R.drawable._28_chicken,
        R.drawable._29_fox,
        R.drawable._30_frog,
        R.drawable._33_cow,
        R.drawable._34_bullfinch,
        R.drawable._35_butterfly,
        R.drawable._36_clown_fish,
        R.drawable._37_penguin,
        R.drawable._38_owl,
        R.drawable._39_crocodile,
        R.drawable._41_bee,
        R.drawable._42_chameleon,
        R.drawable._43_buffalo,
        R.drawable._44_pig,
        R.drawable._46_sheep,
        R.drawable._47_flamingo,
        R.drawable._48_lion,
        R.drawable._50_mouse,
        )
